#!/usr/bin/env bash
#Scrit installs nginx and querry  nginxat root with GET reguest.. using curl
#update server
sudo apt update
#install nginx
sudo apt-get -y install nginx
#allow server to listen on port 80
sudo ufw allow 'Nginx HTTP'
#create a page containing 'helloworld!'
echo 'Hello World' | sudo tee /var/www/html/index.html
#restart the server
sudo systemctl restart nginx
