#!/usr/bin/env bash
#Scrit installs nginx and querry  nginxat root with GET reguest.. using curl
#update server
sudo apt update
#install nginx
sudo apt-get install -y nginx
#allow server to listen on port 80
sudo ufw allow 'Nginx HTTP'
#create an html file 'index.html' containing 'hello World!'
echo 'Hello World!' | sudo tee /var/www/html/index.html
#restart the server
sudo systemctl restart nginx
