#!/usr/bin/env bash
#Sreipt creates a redirection

#text to be inserted inside inside the sed command
replace_with="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch\?v\=QH2\-TGUlwu4 permanent;"

sudo sed -i "s/server_name _;/$replace_with/" /etc/nginx/sites-enabled/default
