#!/usr/bin/env bash
#configue nginx to hace custom error 404 page
replace_with="listen 80 default_server;\n\terror_page 404 \404.html;\n\tlocation = \/404.html {\n\t\troot \/var/www/html;\n\t\tinternal'\n\t}"

sudo sed -i "s/listen 80 default_server;/$replace_with/" /etc/nginx/sites-enabled/default

#create the 404 html page 
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

#restart nginx
sudo service nginx restart
