#!/usr/bin/env bash
#Script configures 2 servers bo be identical
#!/usr/bin/env bash
#Scrit installs nginx and querry  nginxat root with GET reguest.. using curl
#update server
sudo apt update
#install nginx
sudo apt-get -y install nginx
#allow server to listen on port 80
sudo ufw allow 'Nginx HTTP'
#create a page containing 'helloworld!'
echo 'Hello World' | sudo tee /var/www/html/index.html
#remode the /etc/nginx/sites-enabled/default
sudo rm /etc/nginx/sites-enabled/default
#dynamicly linke link /etc/nginx/sites-availabe/ default to ../sites-enabled/
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
#Add a custom Nginx response header to server
replace_with="server_name _;\n\tadd_header X-Served-By $HOSTNAME;"
sudo sed -i "s/server_name _;/$replace_with/" /etc/nginx/sites-enabled/default
#test for error
sudo nginx -t
#restart nginx
sudo systemctl restart nginx
