#!/usr/bin/env bash
#Script implements a load balancer with HAproxy

#update and install HAproxy
sudo apt update
sudo apt install haproxy

#create frontend content
frontend_to_insert="\&;\n\nfrontend html\n\tbind *:80\n\tdefault_backend my_server;"

##write the frontend config
#sudo sed -i "$s/\$/$frontend_to_inseet/" ~/tell

##create backend content
#backend_to_insert="\$;\n\nbackend my_server\n\tbalance roundrobin\n\tserver web-01 34.201.68.249\n\tserver web-02 18.234.106.19"

##configure the cinfig file
#sudo swd -i "$s/\$/$backend_to_insert/" ~/tell

echp  "
frontend dayc.tech
	bind *:80
	default_backend my_servers

backend my_servers
	balance roundrobin
	server web-01 34.201.68.249
	server web-02 18.234.106.19
" >> /etc/haproxy/haproxy.cfg

#start haproxy
sudo service haproxy start
