#!/usr/bin/env bash
#This script configures a server to listen on port 80

#first remove the sites-enabled file
sudo rm /etc/nginx/sites-enabled/default

#next create a dynamic like to link sites-available and sites-enabled
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

#finally restart nginx
sudo systemctl restart nginx
