#!/usr/bin/env bash
#This script prints "Best Schoo" 10 times and on the 9th iteration it prints "hi"
i=0
while [ $i -lt 10 ]
do
	echo "Best School"
	if  [[ $i -eq 8 ]]
	then
		echo "hi"
	fi
	((i++))
done
