#!/usr/bin/env bash
#This script dsiplays the time for 12 hours and 59 minutes
i=1;
j=1;
while [[ $i -le 13 ]]
do
	while [[ $j -lt 60 ]]
	do
		if [[ $i -eq 13 ]]
		then
			if [[ $j -eq 60 ]]
			then
				break
			else
				echo $j
				((j++))
				continue
			fi
		else
			echo $j
		fi
		((j++))
	done
	((j=0))
	echo "Hour $i"
	((i++))
done

